#!/usr/bin/env python3

# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

"""Iterative selected-CI growth driven entirely by SBD's own carryover mechanism.

No qiskit-addon-sqd, no sampled bitstrings anywhere in this driver. Starts from
an explicit alpha/beta determinant file (like run_sbd_diag.py), diagonalizes,
and uses SBD's own --carryover_type machinery -- dominant-determinant selection
by marginal probability, plus (type 2) every single-particle excitation of the
retained half-determinants -- to grow the subspace each round. The returned
carryover_adet/carryover_bdet become next round's adet/bdet directly; nothing
qiskit-addon-sqd-shaped (occupancies, subsampling, configuration recovery) is
involved anywhere, because there is no sampled pool to recover against.

Usage:
    mpirun -np 4 python run_sbd_selected_ci.py \\
        --fcidump ../../vendor/sbd-upstream/data/h2o/fcidump.txt \\
        --adetfile ../../vendor/sbd-upstream/data/h2o/h2o-1em3-alpha.txt \\
        --sbd_carryover_type 2 --sbd_carryover_threshold 1e-3 \\
        --max_iterations 5 --device cpu

    # resume from a previous run's checkpoint instead of --adetfile/--bdetfile
    mpirun -np 4 python run_sbd_selected_ci.py \\
        --fcidump ../../vendor/sbd-upstream/data/h2o/fcidump.txt \\
        --resume_from /tmp/selected_ci_checkpoint.json \\
        --max_iterations 5 --device cpu
"""

import argparse
import json
import re
import sys
import time
from pathlib import Path

import numpy as np


def _cap_to_max_dim(expanded, seed, norb, backend, bit_length, max_dim, rng,
                     ci_strings_fn):
    """Truncate `expanded` to at most max_dim entries.

    Keeps every entry already in `seed` (the set that was just diagonalized,
    so its importance is proven) first, and only randomly subsamples the
    genuinely NEW candidates -- generated by SinglesExtendHalfdets, never
    diagonalized, no amplitude to rank by -- to fill any remaining budget.

    Plain random truncation over the WHOLE expanded set can (and, tested on
    h2o-1em3, does) discard the dominant determinants right along with the
    unimportant ones: energies swung between -31.8/-56.1 Ha and the correct
    ~-76.2 Ha purely depending on which random subset survived. This is the
    same "random subspace gives a meaningless energy" failure mode from
    randomly-sampled bitstrings, showing up again in truncation instead of
    sampling -- same cause (discarding importance information that exists),
    same fix (use what you actually know before falling back to random).
    """
    if len(expanded) <= max_dim:
        return expanded
    seed_strs = set(int(s) for s in ci_strings_fn(seed, norb, backend, bit_length))
    expanded_strs = ci_strings_fn(expanded, norb, backend, bit_length)
    is_seed = np.array([int(s) in seed_strs for s in expanded_strs])
    seed_idx = np.flatnonzero(is_seed)
    new_idx = np.flatnonzero(~is_seed)
    if len(seed_idx) >= max_dim:
        # Even the proven-important set alone exceeds the cap -- keep a
        # random subset of IT, rather than falling back to the unranked
        # candidates just because the seed itself needs trimming too.
        keep = rng.choice(seed_idx, size=max_dim, replace=False)
    else:
        budget = max_dim - len(seed_idx)
        fill = rng.choice(new_idx, size=min(budget, len(new_idx)), replace=False)
        keep = np.concatenate([seed_idx, fill])
    keep = sorted(int(k) for k in keep)
    return [expanded[k] for k in keep]


def parse_fcidump_header(path):
    """Extract NORB, NELEC, MS2 from an FCIDUMP file's header."""
    with open(path) as f:
        header = f.read(2000)
    norb = int(re.search(r"NORB\s*=\s*(\d+)", header).group(1))
    nelec = int(re.search(r"NELEC\s*=\s*(\d+)", header).group(1))
    ms2 = int(re.search(r"MS2\s*=\s*(\d+)", header).group(1))
    return norb, nelec, ms2


def parse_args():
    parser = argparse.ArgumentParser(
        description="Iterative selected-CI growth via SBD's own carryover "
                     "mechanism. No qiskit-addon-sqd, no sampled bitstrings -- "
                     "the subspace grows from SBD's own dominant-determinant "
                     "selection and single-excitation expansion alone.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    # ---- input --------------------------------------------------------------
    io = parser.add_argument_group("Input")
    io.add_argument("--fcidump", required=True, help="Path to FCIDUMP file")
    io.add_argument("--adetfile", default=None,
                     help="Initial alpha determinants. Required unless "
                          "--resume_from is given.")
    io.add_argument("--bdetfile", default="",
                     help="Initial beta determinants (defaults to --adetfile)")

    # ---- the loop -------------------------------------------------------------
    loop = parser.add_argument_group("Selected-CI loop")
    loop.add_argument("--max_iterations", type=int, default=10,
                       help="Hard cap on growth iterations")
    loop.add_argument("--energy_tol", type=float, default=1e-6,
                       help="Stop once the energy change between consecutive "
                            "iterations is below this")
    loop.add_argument("--max_dim", type=int, default=None,
                       help="Cap on strings per spin sector AFTER each "
                            "expansion, so the subspace handed to the next "
                            "iteration cannot exceed max_dim^2. "
                            "--sbd_carryover_ratio/--sbd_carryover_threshold "
                            "cap the PRE-expansion dominant-determinant "
                            "selection; nothing upstream caps the size AFTER "
                            "singles are added, which is where runaway growth "
                            "actually happens (SinglesExtendHalfdets can turn "
                            "a modest retained set into tens of thousands of "
                            "candidates). When the cap bites, it truncates by "
                            "random subsample (fixed seed) -- a safety valve, "
                            "not an importance-ranked truncation: the newly "
                            "generated excited determinants have no amplitude "
                            "yet to rank by.")

    # ---- SBD carryover: the actual expansion mechanism ------------------------
    sbdc = parser.add_argument_group("SBD carryover (the expansion mechanism)")
    sbdc.add_argument("--sbd_carryover_type", type=int, default=2,
                       choices=[0, 1, 2, 3],
                       help="0=disabled -- the loop would never grow. "
                            "1=dominant half-determinants by marginal "
                            "probability p(D)=sum_D' |c_D,D'|^2, no expansion. "
                            "2=type 1 plus every single-particle excitation of "
                            "the retained half-determinants (occupied x "
                            "unoccupied swaps). 3=dominant FULL determinants "
                            "by amplitude, plus their single excitations.")
    sbdc.add_argument("--sbd_carryover_ratio", type=float, default=0.0,
                       help="Fraction of half-determinants retained BEFORE "
                            "expansion, ranked by weight. 0 defers to "
                            "--sbd_carryover_threshold. Used for type 1/2 only.")
    sbdc.add_argument("--sbd_carryover_threshold", type=float, default=1e-3,
                       help="Type 1/2 (ratio=0): cumulative-weight cutoff for "
                            "retained half-determinants. Type 3: direct weight "
                            "cutoff on full determinants.")

    # ---- SBD solver: per-diagonalization, not per loop -------------------------
    solver = parser.add_argument_group("SBD solver")
    solver.add_argument("--sbd_eps", type=float, default=1e-5,
                         help="Davidson stop: residual-vector norm")
    solver.add_argument("--sbd_max_it", type=int, default=10,
                         help="Cap on Davidson iterations")
    solver.add_argument("--sbd_max_nb", type=int, default=10,
                         help="Davidson basis vectors (block size)")
    solver.add_argument("--sbd_method", type=int, default=0,
                         choices=[0, 1, 2, 3],
                         help="0=Davidson, 1=Davidson+Ham, 2=Lanczos, "
                              "3=Lanczos+Ham")
    solver.add_argument("--sbd_bit_length", type=int, default=20,
                         help="Bits packed into each size_t of the bitstring")

    # ---- MPI grid ---------------------------------------------------------------
    mpi = parser.add_argument_group("MPI grid")
    mpi.add_argument("--adet_comm_size", type=int, default=1)
    mpi.add_argument("--bdet_comm_size", type=int, default=1)
    mpi.add_argument("--task_comm_size", type=int, default=1)

    parser.add_argument("--device", choices=["auto", "cpu", "gpu", "gpu-omp"],
                         default="cpu")

    # ---- checkpoint/resume --------------------------------------------------------
    ckpt = parser.add_argument_group("Checkpointing")
    ckpt.add_argument("--checkpoint_path", type=str, default=None,
                       help="Write adet/bdet/energy/iteration to this path as "
                            "JSON text, every --checkpoint_frequency "
                            "iterations, plus always on the last one. Must be "
                            "visible under the same path from every rank -- "
                            "--resume_from has no rank-0-reads-then-broadcasts "
                            "step, every rank opens this path itself.")
    ckpt.add_argument("--checkpoint_frequency", type=int, default=1,
                       help="Write every this many iterations")
    ckpt.add_argument("--resume_from", type=str, default=None,
                       help="Seed the initial adet/bdet from a previous "
                            "--checkpoint_path's last iteration, instead of "
                            "--adetfile/--bdetfile.")

    args = parser.parse_args()
    if args.adetfile is None and args.resume_from is None:
        parser.error("one of --adetfile or --resume_from is required")
    return args


def main():
    args = parse_args()

    import sbd

    sbd.init(device=args.device)
    rank = sbd.get_rank()
    size = sbd.get_world_size()
    backend = sbd.get_backend(args.device)

    norb, nelec_total, ms2 = parse_fcidump_header(args.fcidump)
    num_elec_a = (nelec_total + ms2) // 2
    num_elec_b = (nelec_total - ms2) // 2

    if rank == 0:
        print("=" * 60)
        print("SBD selected-CI: SBD-native subspace growth, no SQD")
        print("=" * 60)
        print(f"MPI ranks: {size}")
        print(f"FCIDUMP: {args.fcidump}")
        print(f"  NORB={norb}, NELEC={nelec_total}, MS2={ms2}, "
              f"Electrons: ({num_elec_a}, {num_elec_b})")
        print(f"Device: {args.device}")
        print("Loop         : "
              f"--max_iterations {args.max_iterations} "
              f"--energy_tol {args.energy_tol:g} "
              f"--max_dim {args.max_dim}")
        print("SBD carryover: "
              f"--sbd_carryover_type {args.sbd_carryover_type} "
              f"--sbd_carryover_ratio {args.sbd_carryover_ratio:g} "
              f"--sbd_carryover_threshold {args.sbd_carryover_threshold:g}")
        print("SBD solver   : "
              f"--sbd_method {args.sbd_method} --sbd_eps {args.sbd_eps:g} "
              f"--sbd_max_it {args.sbd_max_it} --sbd_max_nb {args.sbd_max_nb} "
              f"--sbd_bit_length {args.sbd_bit_length}")
        print("MPI grid     : "
              f"--task_comm_size {args.task_comm_size} "
              f"--adet_comm_size {args.adet_comm_size} "
              f"--bdet_comm_size {args.bdet_comm_size}")

    sbd_data = sbd.TPB_SBD()
    sbd_data.method = args.sbd_method
    sbd_data.eps = args.sbd_eps
    sbd_data.max_it = args.sbd_max_it
    sbd_data.max_nb = args.sbd_max_nb
    sbd_data.bit_length = args.sbd_bit_length
    sbd_data.carryover_type = args.sbd_carryover_type
    sbd_data.ratio = args.sbd_carryover_ratio
    sbd_data.threshold = args.sbd_carryover_threshold
    sbd_data.adet_comm_size = args.adet_comm_size
    sbd_data.bdet_comm_size = args.bdet_comm_size
    sbd_data.task_comm_size = args.task_comm_size

    fcidump = sbd.LoadFCIDump(args.fcidump)

    from sbd.sbd_solver import _ci_strings_to_sbd_dets, _sbd_dets_to_ci_strings

    rng = np.random.default_rng(0)
    start_iteration = 0

    if args.resume_from:
        with open(args.resume_from) as f:
            checkpoint = json.load(f)
        last = checkpoint["iterations"][-1]
        adet_strs = np.array(last["adet_strs"], dtype=np.int64)
        bdet_strs = np.array(last["bdet_strs"], dtype=np.int64)
        adet = _ci_strings_to_sbd_dets(adet_strs, norb, backend, args.sbd_bit_length)
        bdet = _ci_strings_to_sbd_dets(bdet_strs, norb, backend, args.sbd_bit_length)
        start_iteration = last["iteration"]
        if rank == 0:
            print(f"Resuming from {args.resume_from}: iteration "
                  f"{start_iteration}, {len(adet)} alpha / {len(bdet)} beta "
                  "determinants")
    else:
        adet = sbd.LoadAlphaDets(args.adetfile, args.sbd_bit_length, norb)
        bdetfile = args.bdetfile or args.adetfile
        bdet = sbd.LoadAlphaDets(bdetfile, args.sbd_bit_length, norb)

    checkpoint_history = []

    def write_checkpoint(iteration, energy, adet, bdet):
        adet_strs = _sbd_dets_to_ci_strings(adet, norb, backend, args.sbd_bit_length)
        bdet_strs = _sbd_dets_to_ci_strings(bdet, norb, backend, args.sbd_bit_length)
        entry = {
            "iteration": iteration,
            "energy": energy,
            "adet_strs": [int(x) for x in adet_strs],
            "bdet_strs": [int(x) for x in bdet_strs],
        }
        checkpoint_history.append(entry)
        tmp = Path(args.checkpoint_path).with_suffix(".tmp")
        tmp.write_text(json.dumps({"iterations": checkpoint_history}))
        tmp.replace(args.checkpoint_path)

    prev_energy = None
    t_start = time.perf_counter()
    if rank == 0:
        print("Starting selected-CI loop...")

    for i in range(1, args.max_iterations + 1):
        iteration = start_iteration + i
        t0 = time.perf_counter()
        results = sbd.tpb_diag(fcidump, adet, bdet, sbd_data,
                                loadname="", savename="")
        elapsed = time.perf_counter() - t0
        energy = results["energy"]
        co_adet = results["carryover_adet"]
        co_bdet = results["carryover_bdet"]

        dim = len(adet) * len(bdet)
        expanded_dim = len(co_adet) * len(co_bdet)
        if rank == 0:
            print(f"Iteration {iteration}: E={energy:.10f}  "
                  f"dim={len(adet)}x{len(bdet)}={dim:_}  "
                  f"expanded->{len(co_adet)}x{len(co_bdet)}={expanded_dim:_}  "
                  f"({elapsed:.2f}s)")

        due = (i % args.checkpoint_frequency == 0
               or i == args.max_iterations)
        if args.checkpoint_path and rank == 0 and due:
            write_checkpoint(iteration, energy, adet, bdet)

        converged = (prev_energy is not None
                     and abs(energy - prev_energy) < args.energy_tol)
        no_growth = (len(co_adet) == len(adet) and len(co_bdet) == len(bdet))
        if converged or no_growth:
            if rank == 0:
                reason = ("energy converged" if converged
                          else "expansion added nothing new -- subspace is "
                               "closed under the Hamiltonian's dominant "
                               "connections")
                print(f"Stopping: {reason}")
            break

        if args.max_dim is not None:
            co_adet = _cap_to_max_dim(co_adet, adet, norb, backend,
                                       args.sbd_bit_length, args.max_dim, rng,
                                       _sbd_dets_to_ci_strings)
            co_bdet = _cap_to_max_dim(co_bdet, bdet, norb, backend,
                                       args.sbd_bit_length, args.max_dim, rng,
                                       _sbd_dets_to_ci_strings)

        prev_energy = energy
        adet, bdet = co_adet, co_bdet
    else:
        if rank == 0:
            print(f"Stopping: reached --max_iterations {args.max_iterations}")

    if rank == 0:
        total_elapsed = time.perf_counter() - t_start
        print("=" * 60)
        print(f"Final energy: {energy:.10f} Hartree")
        print(f"Final subspace: {len(adet)} alpha x {len(bdet)} beta = "
              f"{len(adet)*len(bdet):_}")
        print(f"Total time: {total_elapsed:.1f}s")
        print("=" * 60)

    sbd.finalize()


if __name__ == "__main__":
    sys.exit(main() or 0)
